### ISSUE TITLE
 Remove additional options in module and component creation 

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#1010]
**Describe the bug**

Description: When creating a new module, the "three dots" are displayed in the upper right corner with the options of delete, edit and copylink. In the two scenarios below, these options have some problems:

Scenario 1: When creating a new module, when clicking on the EDIT and COPYLINK options, nothing happens, when clicking on the DELETE option, a 404 is returned.

Scenario 2: When creating a new component in an existing module, when clicking on the COPYLINK option, nothing happens, when clicking on the DELETE and COPYLINK options, these options are related to the module and not to the component.

**Expected behavior**
As it should be: In these two scenarios this dropdown with these options should no longer be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/42280930/112055153-40b40800-8b35-11eb-9b13-193d5d173f14.png)
![image](https://user-images.githubusercontent.com/42280930/112055203-4e698d80-8b35-11eb-93f1-9d4eaa0336fb.png)

**Comment by monicaribeiro** [comment]
Fixed on #1011
