### ISSUE TITLE
Wrong Butler's Github Action Configuration

### ISSUE THREAD

**Issue by adauto** [ZupIT/charlescd#125]
**Describe the bug**
Missing "charlescd-" prefix in Butler's docker image name on Github Action build and push step.

**Expected behavior**
Butler's docker images should be pushed with "charlescd-" name prefix.

**Screenshots**
![Captura de Tela 2020-06-16 às 15 14 50](https://user-images.githubusercontent.com/1733735/84812041-26685f00-afe4-11ea-9ac4-31949c0a4042.png)

**Comment by maycommit** [comment]
https://github.com/ZupIT/charlescd/pull/124
