### ISSUE TITLE
Wrong configuration name for Charles CD UI

### ISSUE THREAD

**Issue by adauto** [ZupIT/charlescd#127]
**Describe the bug**
CharlesCD UI docker image name doesn't match its module name (charlescd-ui). The same issue exists for its Helm chart folder.

**Expected behavior**
The name should be the same for the docker image, Helm chart folder, and module.

**Screenshots**
![Captura de Tela 2020-06-16 às 15 34 43](https://user-images.githubusercontent.com/1733735/84813911-100fd280-afe7-11ea-8964-6c128fa7997f.png)

**Comment by maycommit** [comment]
https://github.com/ZupIT/charlescd/pull/126
