### ISSUE TITLE
Missing Keycloak JWT authorization header signature validation

### ISSUE THREAD

**Issue by adauto** [ZupIT/charlescd#132]
**Describe the bug**
The JWT authorization token is not being validated by Keycloak.

**To Reproduce**
1. Change the signature segment of a valid CharlesCD JWT authorization token.
2. Make a request to any protected CharlesCD API endpoint using the token as authorization header.
3. See the request succeed.

**Expected behavior**
Any request with an invalid JWT authorization should fail and return the 401 status code.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A autenticidade do token não é verificada pelo nginx, anteriormente era verificado pelo tyk.](https://trello.com/c/Wx1Ku5H9/584-a-autenticidade-do-token-n%C3%A3o-%C3%A9-verificada-pelo-nginx-anteriormente-era-verificado-pelo-tyk)
