### ISSUE TITLE
When creating access tokens, if an error occurs the UI freezes.

### ISSUE THREAD

**Issue by monicaribeiro** [ZupIT/charlescd#1324]
**Describe the bug**
When I try to create a new access token, if I click on the button to create it and any error happens between the communication UI-BACKEND, the UI will freeze and the 'create button' turns into a forever loading icon.

**To Reproduce**
1. Log in with Admin profile.
2. Click on 'Access Token' menu.
3. Fill all the information to create your access token.
4. Click on save and see error (force your service to return an error).

**Expected behavior**
I expect a clear error message that help me to understand the error. Also, I expect that the loading button turning into the save button again.

**Your Environment**
- CharlesCD version used: 1.0.0

**Comment by SchumaiquerZup** [comment]
Issue closed, it was resolved in https://github.com/ZupIT/charlescd/pull/1345
