### ISSUE TITLE
Check the Docker Logo in the image

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/charlescd#1338]
There is a docker logo on the website; please, check out if the symbol follows the trademark once the emblem belongs to Docker Inc.

Ref: https://charlescd.io/

> The Docker’s registered, unregistered and pending logos, including the Docker “Moby Dock” whale logo, as well as other design elements such as characters and container images, may be taken only from Docker’s product sheet or from Docker’s service screen shot following authorization from us. Do not create imitations, facsimiles or reproductions of these design elements on your own. The design elements may only appear with the words, logotype, graphic elements and spacing which Docker has previously approved for use and may not be modified, recombined or displayed in modified scenes, images or other artwork.

Ref: https://www.docker.com/legal/trademark-guidelines

**Comment by guilhermemartinsdeoliveirazup** [comment]
Docker logo has been updated.
