### ISSUE TITLE
All users are being created as root

### ISSUE THREAD

**Issue by adauto** [ZupIT/charlescd#134]
**Describe the bug**
The "root" checkbox is missing on "user" CRUD, and therefore all users are being created as root.

**To Reproduce**
1. Log in as root.
2. Go to the Users section.
3. Click on the "Create user" button.

**Expected behavior**
The "root" checkbox should be present and its value should be sent in create/update user API requests.

**Screenshots**
![Captura de Tela 2020-06-18 às 19 05 30](https://user-images.githubusercontent.com/1733735/85076551-b6e6a100-b196-11ea-96e0-c62db7190bc4.png)

![Captura de Tela 2020-06-18 às 19 07 07](https://user-images.githubusercontent.com/1733735/85076758-2d839e80-b197-11ea-9ede-8eb523becf42.png)

![Captura de Tela 2020-06-18 às 19 08 37](https://user-images.githubusercontent.com/1733735/85076739-252b6380-b197-11ea-8ff0-73ecbb21406b.png)

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Todos os usuários estão sendo criados como root (parametro isRoot igual a true).](https://trello.com/c/TrKgljmB/573-todos-os-usu%C3%A1rios-est%C3%A3o-sendo-criados-como-root-parametro-isroot-igual-a-true)
