### ISSUE TITLE
Can't make any action on application with a systemic token with "maintenance_write" permission

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#1363]
**Describe the bug**
When creating a system token with maintainer permission ("maintenance_write") it is not possible to access charles actions such as creating modules and circles. For these actions returns 403

**To Reproduce**
1- Create a system token with "maintenance_write" permission.
2- Try to create a module with this system token
3- See the error with the return of 403

**Expected behavior**
It should be possible to successfully create modules and circles

**Comment by SchumaiquerZup** [comment]
Thanks for your comment, it is already being analyzed and resolved. To follow the status just follow this PR https://github.com/ZupIT/charlescd/pull/1368
