### ISSUE TITLE
 Error while installing chart from version 1.0.1

### ISSUE THREAD

**Issue by joaoinaciozup** [ZupIT/charlescd#1401]
**Describe the bug**
I downloaded the release 1.0.1 and tried to install, but there is an error on the postgresql pod informing there is no password for user postgres.

**To Reproduce**
1. Download release 1.0.1 from github
2. Update chart dependencies (helm dependency update)
3. Install the chart

**Expected behavior**
Have charlescd up and running

**Screenshots**

![image](https://user-images.githubusercontent.com/67961431/128920954-58bbd539-6c2f-4a33-815d-e3e5708f2c1b.png)
![image](https://user-images.githubusercontent.com/67961431/128920889-1a1e5bb2-af7e-4620-97b3-11bfcc669d20.png)

**Your Environment**
- CharlesCD version used: 1.0.1
- Description of environment where CharlesCD is running: Tested on local cluster (kind) and GKE (1.19.9-gke.1900)

**Additional context**
First I tried a custom version of the chart changing the secrets on the chart and got the error, then I tried the default version that comes in the release and got the same error.

**Comment by lucasmachadozup** [comment]
Hello @joaoinaciozup, after the first installation (with custom values), did you remove the remaining persistent volume claim from the cluster?
Probably the old PVC caused this problem, I tried to replicate it here in new installations and I didn't find the same error.

Could you try again with attention to this detail?
If the error persists, let us know and we'll look for the solution together.

**Comment by lucasmachadozup** [comment]
Here we have the user and password for postgres: 
- https://github.com/ZupIT/charlescd/blob/main/install/helm-chart/values.yaml#L645

And here the Job that trigger the script to create users and databases: 
- https://github.com/ZupIT/charlescd/blob/main/install/helm-chart/templates/initdb-job.yaml#L34

The Script:
- https://github.com/ZupIT/charlescd/blob/main/install/helm-chart/templates/postgres-cm.yaml

**Comment by joaoinaciozup** [comment]
Closing, it was the persistent volume that I forgot to erase, thanks @lucasmachadozup
