### ISSUE TITLE
"Undeploy" option is enabled on the menu of Default circle

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#143]
Undeploy option is enabled on the menu of Default circle

**To Reproduce**
1. Login on CharlesCD
2. Click on "Workspaces" and select a workspace 
3. Click on "Circles" and filter by "Inactive"
4. Click on "Default"
4. Click on the menu of the default circle to see the error: Undeploy option is listed

**Expected behavior**
It Is expected the interface doesn't show the "Undeploy" option when the circle is "Default"

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Undeploy" option is enabled on the menu of Default circle](https://trello.com/c/MXOcmytT/597-undeploy-option-is-enabled-on-the-menu-of-default-circle)

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The "Undeploy" option is active when a release is deploying](https://trello.com/c/soj2h3Ke/640-the-undeploy-option-is-active-when-a-release-is-deploying)
