### ISSUE TITLE
CharlesCD UI is making several requests to /moove/v2/users/{email-as-base64} endpoint during login time

### ISSUE THREAD

**Issue by adauto** [ZupIT/charlescd#145]
**Describe the bug**
The CharlesCD UI is making several requests to /moove/v2/users/{email-as-base64} endpoint during login time.

**To Reproduce**
1. Open browser's developer tools.
2. Go to the "network" section.
3. Access CharlesCD Login screen.
4. Insert username and password into the login form.
5. Click in to '"continue" button.
6. See error.

**Expected behavior**
CharlesCD UI should call  /moove/v2/users/{email-as-base64}  once.

**Screenshots**
![Captura de Tela 2020-06-22 às 17 56 01](https://user-images.githubusercontent.com/1733735/85334459-acd3e380-b4b1-11ea-825c-019e5f98b3f5.png)

![Captura de Tela 2020-06-22 às 17 54 39](https://user-images.githubusercontent.com/1733735/85334376-8a41ca80-b4b1-11ea-880a-60984487c5a1.png)

![Captura de Tela 2020-06-22 às 17 55 08](https://user-images.githubusercontent.com/1733735/85334385-8dd55180-b4b1-11ea-9c37-21d897f04d06.png)

**Comment by ifdouglas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Requisição duplicada para buscar usuário por email após o login](https://trello.com/c/hW2ruUV9/579-requisi%C3%A7%C3%A3o-duplicada-para-buscar-usu%C3%A1rio-por-email-ap%C3%B3s-o-login)
