### ISSUE TITLE
More than one tab opened for the same circle

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#146]
**Describe the bug**
More than one tab is being opened for the same circle, depending on the number of clicks on the circle.

**To Reproduce**
1. Login on CharlesCD
2. Click on "Workspaces" and select a workspace
3. Click on "Circles" 
4. Click on the same circle more than once to see the error: More than one tab will be opened for the same circle

**Expected behavior**
It is expected that just one tab is opened by circle, even if I click in the same circle several times.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [More than one tab opened for the same circle](https://trello.com/c/gqwAY8K6/598-more-than-one-tab-opened-for-the-same-circle)
