### ISSUE TITLE
I'm not logged out when session expires

### ISSUE THREAD

**Issue by monicaribeiro** [ZupIT/charlescd#164]
**Describe the bug**
After X minutes my login session expires, however, I'm not logged out. 
I receive an error (403 FORBIDDEN), but Charles UI continues there loading something forever and I do not know what is going on (as a user, it's not clear that my session ended).

**To Reproduce**
0. Open network log at your browser.
1. Login.
2. Access a workspace.
3. Wait for 15 min (I don't know the time it takes to expire)
4. Do a request to list hypothesis.
5. See error.

**Expected behavior**
When session expires, I expect to be logged out.

**Screenshots**
After doing the steps to reproduce the behavior, you'll have something like:
![image](https://user-images.githubusercontent.com/7025960/85601762-0b6d9e80-b625-11ea-8264-cc294dd2dd5f.png)

The response will be: _'jwt signature verification failed: 'exp' claim expired at Wed, 24 Jun 2020 16:18:08 GMT'_

**Your Environment**
- CharlesCD version used: 0.2.12
- Browser Name and version (if applicable): Chrome Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I'm not logged out when session expires](https://trello.com/c/eOmgU2TL/604-im-not-logged-out-when-session-expires)
