### ISSUE TITLE
All paginations on Charles using JDBC template are wrong

### ISSUE THREAD

**Issue by emiteze** [ZupIT/charlescd#168]
**Describe the bug**
Since we changed to JDBC template approach, all paginations that we implemented are being applied to the number of rows returned by the query, and the query in some cases returns more than one line for the same object that are being queried and paginated. Since our frontend does not query for a specific size, our application assumes Springs' default size which is 20, and then this size is applied on the LIMIT parameter in each query.

**To Reproduce**
Steps to reproduce the behavior (user group use case):
1. Create a user group called A_User_Group
2. Associate 20 members to that user group
3. Create one more user group called B_User_Group
4. Call the find all user groups API and note that it only returns the first user group created.

**Expected behavior**
All paginated APIs should apply the LIMIT parameter to each object being queried, not for each line on the resultset, or we should change our query to return one object by line.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All paginations on Charles using JDBC template are wrong](https://trello.com/c/5H8zRPyA/607-all-paginations-on-charles-using-jdbc-template-are-wrong)
