### ISSUE TITLE
Charles is not paginating on docker hub registry integration when the number of tags in registry is greater than 100

### ISSUE THREAD

**Issue by emiteze** [ZupIT/charlescd#169]
**Describe the bug**
Today we only search for the first 100 tags ordered by name on user's Docker Registry.

**To Reproduce**
1. Create a new registry configuration and register a new module that have more than 100 tags.
2. Try to search for your tags on the override release screen on any circle.
3. Note that only the first 100 tags are being returned.

**Expected behavior**
We should have pagination on backend for this service.

**Comment by adauto** [comment]
#241

**Comment by adauto** [comment]
Docker registry's V2 REST API does not offer a way to query image tags by its name, so we decide to remove the current fake pagination that frontend performs and we will ask users to inform the tag full name to check if it exists or not. #241
