### ISSUE TITLE
OCTOPIPE_URL and DARWIN_ISTIO_DEPLOYMENT_CALLBACK variables are missing inside the helm install files

### ISSUE THREAD

**Issue by lucasbfernandes** [ZupIT/charlescd#171]
**Describe the bug**
Today, when installing charles via the tutorial, deployments won't work because of two missing environment variables inside the charlescd-butler yaml.

**To Reproduce**
1. Install Charles
2. See the error

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OCTOPIPE_URL and DARWIN_ISTIO_DEPLOYMENT_CALLBACK variables are missing inside the helm install files](https://trello.com/c/LeLUPD6l/631-octopipeurl-and-darwinistiodeploymentcallback-variables-are-missing-inside-the-helm-install-files)
