### ISSUE TITLE
Circle matcher throws "java.util.NoSuchElementException: Default circle metadata not found." when workspaceID not exists.

### ISSUE THREAD

**Issue by lucassaleszup** [ZupIT/charlescd#180]
**Describe the bug**
Circle matcher throws "java.util.NoSuchElementException: Default circle metadata not found." when workspaceID not exists.

**To Reproduce**
1.Call /identify with non existent workspaceId.
2. Return message is ok, but the Stdout prints "java.util.NoSuchElementException: Default circle metadata not found."

**Expected behavior**
Circle Matcher should returns message telling that the "workspace not exists"

**Comment by SchumaiquerZup** [comment]
It was reproduced, it's bug no longer occurs
