### ISSUE TITLE
Opened module do not highlight in menu

### ISSUE THREAD

**Issue by ifdouglas** [ZupIT/charlescd#197]
### Describe the bug
The opened module do not highlight in menu.

**To Reproduce**
1. Login on CharlesCD.
2. Click on "Workspaces" and select a workspace.
3. Click on "Modules".
4. Click on a module and see that the line in the menu will not highlighted as a selected one.

### Expected behavior
It is expected that the opened module is highlighted in the menu.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Opened module do not highlight in menu.](https://trello.com/c/gp4UrsLS/630-opened-module-do-not-highlight-in-menu)
