### ISSUE TITLE
Implement sorting and paging in all list resources

### ISSUE THREAD

**Issue by eliasalveszup** [ZupIT/charlescd#231]
To apply design patterns and avoid future problems related to high data volume, it is necessary to implement sorting and paging in all resources that can return a list of objects.
Following good practices, the approach must be:

**Sorting**

Expect the optional **sort** query param, having as value a comma separated list of properties, indicating the sort priority.
Each property is ordered ascending (**:asc** suffix) by default. So, to order descending, the property name must be suffixed by **:desc**.

Examples:
- /deployments?sort=createdAt
- /deployments?sort=createdAt:desc,title
- /deployments?sort=createdAt:asc,createdBy:asc,title

**Paging**

Use optional **page** and **size** query params (mutually required) to indicate the page size and offset, respectively. Both params must be integers bigger than zero.

Examples:
- /deployments?page=1&size=10
- /deployments?page=100&size=5

The default **page** is **1** and **size** is **10**.

**Comment by kaduartur** [comment]
Hello @eliasalveszup, I'm interested in contributing.

Could you assign me to this issue?

**Comment by monicaribeiro** [comment]
Hi, @kaduartur 
Thank you for your interest in contributing :) 
If you have any question, count on me.
