### ISSUE TITLE
When inserting a 68 character url, two characters pass from the "circle matcher" card layout

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#235]
**Describe the bug**
When inserting a 68 character url, two characters pass from the "circle matcher" card layout as in the image

**To Reproduce**
1. Access the Configuration screen;
2. Access Credentials screen;
3. In the circle matcher section, insert 68 characters according to the attachment image pattern: https://xxxx-xxxxxxx.xxxxxxxxxxxxxxxxxx.xxx/xxxxxxxxx-xxxxxx-xxxxxxx

**Expected behavior**
The entire url is expected to be inside the card.

**Screenshots**
<img width="512" alt="evidence" src="https://user-images.githubusercontent.com/42280930/86410007-64c27700-bc90-11ea-9125-71421f35708c.png">

**Your Environment**
- CharlesCD version used: 0.2.12
- Browser Name and version (if applicable): Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit).

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When inserting a 68 character url, two characters pass from the "circle matcher" card layout](https://trello.com/c/RaaMGSxy/642-when-inserting-a-68-character-url-two-characters-pass-from-the-circle-matcher-card-layout)
