### ISSUE TITLE
Updating previous deployment status incorrectly

### ISSUE THREAD

**Issue by emiteze** [ZupIT/charlescd#242]
**Describe the bug**
This scenario occurs only in the open sea's use case. If we do a deploy with success of a release with 5 components and then later we ask for a deploy that don't contains all components from open sea, we are updating the status of previous deploy to NOT_DEPLOYED, then resulting in a wrong payload of which components are deployed for that circle.

And we are not looking for the callback status to update previous deploy too. We should only update the previous deploy for that circle if the callback status were successfull for deploy or undeploy.

It's important to note that the virtual services probably would be ok and the deployments too, but moove does not represent what really is deployed in terms of components for open sea.

**To Reproduce**
1. Do a successfull deploy in open sea with N components
2. Ask for a deploy with N-1 components
3. Note that the previous deploy containing N components will be updated to NOT_DEPLOYED.
4. This will result in a wrong payload on circle's screen (showing only N-1 components).

**Expected behavior**
We should have a concise representation from what is applied on user's cluster in terms of deployments and virtual services.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updating previous deployment status incorrectly](https://trello.com/c/c2sDnBb8/641-updating-previous-deployment-status-incorrectly)
