### ISSUE TITLE
When a circle is deleted the circle list is not updated

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#244]
**Describe the bug**
When a circle is deleted the circle list is updated just when I reload the page.

**To Reproduce**
1. Login in the system;
2. Select a workspace;
3. Click on "Circles" and select a circle;
4. Go to the circle menu and delete the circle;

**Expected behavior**
The circle list should be updated when a circle is deleted.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When a circle is deleted the circle list is not updated](https://trello.com/c/BbzPPNWw/639-when-a-circle-is-deleted-the-circle-list-is-not-updated)

**Comment by angelicalimazup** [comment]
This issue was solved.

**Comment by ifdouglas** [comment]
This behavior doesn't happen anymore. Probably fixed in https://github.com/ZupIT/charlescd/pull/196
