### ISSUE TITLE
The "Override release" option is active when a release is deploying

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#246]
**Describe the bug**
The "Override release" option shouldn't be active when a release is deploying.

**To Reproduce**
Login in the system
Select a workspace
Click on "Circles" and select a circle
Deploy a release

See that the "Override release" option on the menu of the circle is active when the release still deploying.

**Expected behavior**
The "Override release" option shouldn't be active when the release is not deployed yet.

**Comment by monicarib** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The "Override release" option is active when a release is deploying](https://trello.com/c/KklojMSF/638-the-override-release-option-is-active-when-a-release-is-deploying)
