### ISSUE TITLE
Charles doesn't undeploy the successful pods of the release when a release component fails

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#252]
**Describe the bug**
When I deploy a release that contains a module that fails to deploy, the pods that were deployed with success still run, generating an inconsistent release.

**To Reproduce**
1. Deploy a release that contains modules that deploy with success and a module that fails;
2. Wait for the error
3. Check the pods on Kubernetes;

See that the pods that were successful are not undeployed.

**Expected behavior**
It is expected that if a release component fails to deploy, all components of the release should be undeployed.

**Comment by angelicalimazup** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Charles doesn't undeploy the successful pods of the release when a release component fails](https://trello.com/c/UWLD96ch/644-charles-doesnt-undeploy-the-successful-pods-of-the-release-when-a-release-component-fails)

**Comment by lucasbfernandes** [comment]
https://github.com/ZupIT/charlescd/pull/478 fixes this @angelicalimazup
