### ISSUE TITLE
Tooltips with documentation are redirecting to 'Not Found' page

### ISSUE THREAD

**Issue by monicaribeiro** [ZupIT/charlescd#277]
**Describe the bug**
There are some tooltips that redirects to a documentation page. However, some of them are "not found'.

**To Reproduce**
1. Open Modules
2. Create Module
3. Click on the tooltip located on the right side of "Create module" title.
4. Click on "View documentation".

**Expected behavior**
I expect to open a documentation link equivalent to the topic I'm looking for.

**Comment by ifdouglas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltips with documentation are redirecting to 'Not Found' page.](https://trello.com/c/wkD6tGvi/653-tooltips-with-documentation-are-redirecting-to-not-found-page)
