### ISSUE TITLE
typo trevis on charlescd/docs/arquitetura-do-sistema.md image

### ISSUE THREAD

**Issue by fandujar** [ZupIT/charlescd#41]
**Describe the bug**
Typo on image on charlescd/docs/arquitetura-do-sistema.md. It should be Travis not Trevis.

**To Reproduce**
1. Acess charlescd/blob/master/docs/arquitetura-do-sistema.md
2. Check image
3. Check CI part

**Expected behavior**
Travis as an example of CI integration

**Screenshots**
not applicable

**Your Environment**
- CharlesCD version used: n/a
- Description of environment where CharlesCD is running: n/a
- Browser Name and version (if applicable): n/a

**Additional context**
n/a

**Comment by monicarib** [comment]
Hi, @fandujar! Thank you for your feedback. 
We fixed this issue and our master is updated.
