### ISSUE TITLE
When trying to log in with wrong credentials a 401 error appears on the UI 

### ISSUE THREAD

**Issue by angelicalimazup** [ZupIT/charlescd#410]
**Describe the bug**
When trying to log in with wrong credentials a 401 error appears on the UI
**To Reproduce**
Steps to reproduce the behaviour:
1. Access the login page
2. Insert the wrong credentials and try to log in

**Expected behaviour**
It is expected that the UI shows a message that clearly explains what is the error,

**Comment by ricardorames** [comment]
Fixed on release [0.7.1](https://github.com/ZupIT/charlescd/releases/tag/0.7.1).
