### ISSUE TITLE
Api to search for specific users UserGroups does not work.

### ISSUE THREAD

**Issue by SchumaiquerZup** [ZupIT/charlescd#422]
**Describe the bug**
When searching for a specific user group back returns all.

**To Reproduce**
1. Access application with an admin user
2. Select User Groups
3. Think about a valid user group

**Expected behavior**
The service is expected to return only the specified user group

**Screenshots**

**Comment by monicaribeiro** [comment]
Closed by: https://github.com/ZupIT/charlescd/pull/428

**Comment by monicaribeiro** [comment]
Closed by: https://github.com/ZupIT/charlescd/pull/428
