### ISSUE TITLE
 When clicking outside to edit the user's avatar photo fields disappear

### ISSUE THREAD

**Issue by SchumaiquerZup** [ZupIT/charlescd#425]
**Describe the bug**
When selecting the users screen and clicking on a user without a valid photo and trying to edit the user's photo by clicking on a different place, field disappears.

**To Reproduce**
1. Access the application
2. Select the user option
3. Select a user without a photo
4. Click to edit user photo
5. Click anywhere else

**Comment by Anirudhkarnam** [comment]
@SchumaiquerZup 

Could you please assign this to me and guide me how to access the application and check the issue.

Thanks
