### ISSUE TITLE
Inactive circles should not be returned in the circle-matcher service.

### ISSUE THREAD

**Issue by lucassaleszup** [ZupIT/charlescd#440]
**Describe the bug**
Due to inactive circles we lose control of who can be affected by the profiles created in new circles.

**To Reproduce**
1. Create circle with age > 30 and don't deploy
2. Create another circle with age > 20 and deploy one version
3. Circle matcher responds with both circle Ids if age > 30.

**Expected behavior**
Circle matcher must respond with only active circles!

**Comment by barbararochazup** [comment]
Fixed on release [0.3.11](https://github.com/ZupIT/charlescd/releases/tag/0.3.11l)
