### ISSUE TITLE
 "Update" button in "Add/Remove User" modal in User Groups does not appear on small screens

### ISSUE THREAD

**Issue by pedroborgeszup** [ZupIT/charlescd#445]
**Describe the bug**
"Update" button in the "Add / Remove User" modal in User Groups does not appear on small screens (tested resolution: 1366 x 768) in cases where the user list has 5 or more users. Appears to work correctly at higher resolutions (tested resolution: 1920 x 1080).

**To Reproduce**
1. Login with root user, so you have access to User Group.
2. Enter User Group tab.
3. Create a User Group with 5 or more users or just enter a User Group with 5 or more users.
4. Click "Add / Remove user" button.
5. See error

**Expected behavior**
When scrolled down on "Add / Remove user" modal should appear "Update" button

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/42281099/91606523-954d2700-e948-11ea-95b5-b402b59e9bae.png)
![Screenshot_2](https://user-images.githubusercontent.com/42281099/91606528-98481780-e948-11ea-8ba9-23f6452a0f6a.png)

**Your Environment**
- CharlesCD version used: DEV
- Description of environment where CharlesCD is running:
- Browser Name and version (if applicable): Chrome

**Additional context**

**Comment by osmarpetry** [comment]
I could fix that, but I unable to create a local environment with Charles to test it. Can someone provide me an open demo API? 

In the code, the only button with `Update` text, doesn't have a '@media', conditional, or some library to reproduce the `@media` with Javascript

**Comment by bCatanant** [comment]
@osmarpetry we are working on improving our mock environment, as soon as this update is finished it will be possible to start the application locally for testing.
