### ISSUE TITLE
504 gateway timeout on charlescd-villager requests

### ISSUE THREAD

**Issue by lucasbfernandes** [ZupIT/charlescd#447]
**Describe the bug**
Sometimes the requests that charlescd-moove make to charlescd-villager return with a 504 Gateway Timeout.

**To Reproduce**
1. Compose a new release with available images;
2. Name the release;
3. Select a module;
4. Select a component;
5. Copy and paste the image tag;
6. Sometimes the request for the tags/ service won't leave the (Pending) state until a 504 timeout happens;

**Expected behavior**
The request will complete ASAP with a 200 OK  status.

**Screenshots**
The request for https://charles-url/moove/v2/modules/:moduleId/components/:componentId/tags?name=image-tag with a 504 Gateway Timeout status:

![504villager](https://user-images.githubusercontent.com/4423726/91609741-58842e80-e94e-11ea-8ed3-def4aa351b47.jpeg)

**Your Environment**
- Description of environment where CharlesCD is running: K8S charles-dev cluster
- Browser Name and version (if applicable): Google Chrome v84.0.4147.135

**Comment by lucassaleszup** [comment]
probably fixed by that PR: https://github.com/ZupIT/charlescd/pull/442
