### ISSUE TITLE
Charles is missing out on implanting with a bigger name than supported

### ISSUE THREAD

**Issue by SchumaiquerZup** [ZupIT/charlescd#458]
**Describe the bug**
Although there is validation (of the image name size) in the build generation. It is not taken into account that at the time of the deployment, the component name plus the image tag are concatenated.

**To Reproduce**
1. Have a build with the name of 60 characters
2. Deploy with the circle matcher module
3. See error

**Comment by lucasbfernandes** [comment]
The PR https://github.com/ZupIT/charlescd/pull/459 fixes this.

**Comment by eliasalveszup** [comment]
Fixed in Butler v2.
