### ISSUE TITLE
Confirm branch deletion when deleting card

### ISSUE THREAD

**Issue by eliasjsalves** [ZupIT/charlescd#475]
When deleting any card in hypothesis board, the branch associated to it is also deleted. This behavior can be dangerous if the associated branch was created by any flow outside Charles.

**To Reproduce**
1. Create any card on hypothesis board
2. Delete the card
3. Verify that the associated branch is alto deleted

**Expected behavior**
Branches named as **master** or **develop** should never be deleted. For other cases, a confirmation message show be displayed to the user, asking if the branch should be removed or not.

**Comment by barbararochazup** [comment]
Development started: branch [issue-475-card-deletion](https://github.com/ZupIT/charlescd/tree/issue-475-deletion-card-branch)
