### ISSUE TITLE
Write a doc session about user profile functions

### ISSUE THREAD

**Issue by barbararochazup** [ZupIT/charlescd#564]
**Description:**
Write a doc session about user profile functions:

- Password Change;

**Expected:**

A new topic 'Users' on 'Reference' in the doc with profile functions explanations and examples.

**Tips:** Use step-by-step and images

_See example:_ 

https://github.com/ZupIT/charlescd-docs/blob/master/reference/users-group.md

https://github.com/ZupIT/charlescd-docs/blob/master/reference/cd-configuration.md

**Comment by ng29** [comment]
Hey @barbararochazup 
Is this issue up for grabs , so that can pick it up ? 

Cheers

**Comment by barbararochazup** [comment]
Yes! I assign to you

**Comment by ng29** [comment]
> Yes! I assign to you

Hey @barbararochazup , i have got assigned other issues of AWS too and have bandwidth issues so not sure will be able to cater this too, unassigning from myself , will pick it up after clearing my plate. 

Cheers
