### ISSUE TITLE
Profile information not showing the user groups associated to user

### ISSUE THREAD

**Issue by barbararochazup** [ZupIT/charlescd#566]
**Describe the bug**
When you access profile information (it could be your profile or other people's profile, it is not showing the user groups associated to user.

**To Reproduce**
1. Go to Account screen;
2. Click on Profile;
3. Profile information will show without User group list;

**Expected behavior**
Show user-group list that user is associated

![image](https://user-images.githubusercontent.com/68229507/95200057-21f2cc80-07b4-11eb-940a-20633dcf694a.png)

**_Tips:_**

Change ```moove/v2/users/{email}``` service

_Backend:_
- Add a new properties with user groups info in UserResponse

"userGroups":[
      {
         "id":"daskoadksdsa",
         "name":"USER_GROUP_A"
      },
      {
         "id":"daskoadksdsa",
         "name":"USER_GROUP_B"
      }
   ]

_Frontend:_

Show user-group information according new properties in UserResponse

**Comment by somstrom** [comment]
@barbararochazup

Could you please assign this to me ?

**Comment by barbararochazup** [comment]
Hi @somstrom 

I assign this to you.

Thank you for contributing!
