### ISSUE TITLE
When you click on create card button, the card is not created.

### ISSUE THREAD

**Issue by barbararochazup** [ZupIT/charlescd#567]
**Describe the bug**

When you click on create card button, the card is not created. Only when pressing 'Enter' the action ocurrs.

**To Reproduce**
1. Go to Hypothesis board;
2. Click on Create Card;
3. Enter card name
3. Click Create Card again;

**Expected behavior**
A card is expected to be created when I click the button.

**Comment by Anirudhkarnam** [comment]
Hi Barbara,

Could you please assign this to me and give more details on this.

**Comment by barbararochazup** [comment]
Hi @Anirudhkarnam ,

I assign this to you.

Well, the bug occurs on the Hypothesis Board: Hypotheses > Any Option on List

![hypothesis menu 2](https://user-images.githubusercontent.com/68229507/95392936-0250c680-08d0-11eb-85e4-91211ec27c6b.png)

On the example I click in 'Teste'.A board with Create Card Option appears:

![create card 1](https://user-images.githubusercontent.com/68229507/95392910-f8c75e80-08cf-11eb-811a-2d988a3fc0af.png)

When I click on Create Card, a field to fill card name appears:

![button](https://user-images.githubusercontent.com/68229507/95393090-5a87c880-08d0-11eb-9159-616d763880ac.png)

Today, after filling the card name, I only had to press the Enter Button and the Card was created. The expected behavior, When I click in Create Card Button  is for the card to be created too.

Thank you for contributing!

**Comment by Anirudhkarnam** [comment]
Hi @barbararochazup 

Thanks for assigning. Do i have to login to the application with a new account, to check the issue

**Comment by Anirudhkarnam** [comment]
@barbararochazup 
Could you please tell me more on this. I am not able to login to check the exact error.
