### ISSUE TITLE
Lower than not working in circle-matcher

### ISSUE THREAD

**Issue by thallesfreitaszup** [ZupIT/charlescd#618]
**Describe the bug**
Rule lower than not working in circle matcher

**To Reproduce**
1. Create a circle with the condition lower than
2. Call identify in the circle matcher with the key of that rule
4. See error( {"code":"INVALID_PAYLOAD","message":"status 400 reading CircleMatcherClient#identify(URI,IdentifyRequest)"}

**Expected behavior**
Error not be thrown when using lower than condition

**Screenshots**
![image](https://user-images.githubusercontent.com/56738340/96594631-37dab400-12c1-11eb-91f6-1af28f86ecd8.png)

![image](https://user-images.githubusercontent.com/56738340/96594491-0d88f680-12c1-11eb-8602-35dc941132f2.png)

**Your Environment**
- CharlesCD version used: 0.3.11

**Comment by eliasalveszup** [comment]
Solved in version 0.5.7.
