### ISSUE TITLE
User with developer access can't access workspace

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#641]
**Describe the bug**
When adding a usergroup to the workspace and assigning access as a developer, and logging in with some user of that usergroup he cannot access the workspace.

**To Reproduce**
1. As an admin, assign a usergroup to a worspace;
2. Put the type of access as developer;
3. Exit the application;
4. Log in as a user of that usergroup.
5. See error

**Expected behavior**
The expected behavior would be that the user could access the standard workspace as a developer

**Screenshots**
![image](https://user-images.githubusercontent.com/42280930/97316009-12612380-1848-11eb-8436-d6b539b5b420.png)
![image](https://user-images.githubusercontent.com/42280930/97316121-29077a80-1848-11eb-8084-c9b7c4763563.png)
![image](https://user-images.githubusercontent.com/42280930/97316206-3f153b00-1848-11eb-895c-af8c09e49b74.png)
![image](https://user-images.githubusercontent.com/42280930/97316300-57855580-1848-11eb-95c5-72f78da9e40e.png)
![image](https://user-images.githubusercontent.com/42280930/97316361-6b30bc00-1848-11eb-841b-5a4971b84618.png)

**Comment by pedroborgeszup** [comment]
This bug still happening

**Comment by pedroborgeszup** [comment]
Fixed
