### ISSUE TITLE
When saving release without a name, the front freezes

### ISSUE THREAD

**Issue by monicaribeiro** [ZupIT/charlescd#757]
**Describe the bug**
When I try to save a release in a circle without setting the name of the release, I do not receive any error message in the front end, however, in the backend there is an error saying that I need to fill the field.

**To Reproduce**
1. Create a circle
2. Save a segment
3. Click and Release and Create Release
4. Fill the module, component and version, however let the "RELEASE NAME" black.
5. Click on save.
6. See the error.

**Expected behavior**
I expect that I was clear that Release Name is an obligatory field, and also warn me if I try to save it without a name.

**Screenshots**

![chrome-capture (8)](https://user-images.githubusercontent.com/7025960/102390817-aaab9700-3fb3-11eb-904c-4e6d3544c1b7.gif)

![image](https://user-images.githubusercontent.com/7025960/102390861-b72fef80-3fb3-11eb-97ed-504212d494d9.png)

**Your Environment**
- CharlesCD version used: 0.4.5

**Comment by SchumaiquerZup** [comment]
the problem no longer occurs in the version https://github.com/ZupIT/charlescd/releases/tag/1.0.1
