### ISSUE TITLE
Default circle Id changed after upgrading charles

### ISSUE THREAD

**Issue by joaoinaciozup** [ZupIT/charlescd#760]
**Describe the bug**

I upgraded the charlescd with helm from version 4.0.1 to 4.0.5, and it upgraded successfully, but when I deployed a component on default cricle I got two pods running, then I noticed that the id for the default circle had changed. To fix the issue I deleted the deployments for the Id that was running before the version upgrade and deployed all my components again on deafult circle.

The same issue happened in two distinct environments (gke clusters)

**To Reproduce**
1. Install CharlesCD with helm for version 4.0.1
2. Deploy some components on default circle
3. Upgrade charles with helm to version 4.0.5
4. Deploy a module on default circle

**Expected behavior**
The circle Id shouldn't change.

**Your Environment**
- CharlesCD version used: 4.0.5
- Description of environment where CharlesCD is running: GKE with istio 1.4.10

**Comment by thallesfreitaszup** [comment]
hello @joaoinaciozup , thanks for contributing. This issue is specific to the migration from version 0.4.1 to 0.4.2 where the default circle id that was static became dynamic. We even started to create a migration script but it wasn't possible, this problem won't happen in future versions.
