### ISSUE TITLE
 It is not possible to create a release with more than one card on the hypothesis board

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#784]
**Describe the bug**
On the hypothesis board when selecting more than one card to create a release, the system throws this error code:
`GIT_ERROR_BRANCH_NOT_FOUND", message: "Branch main not found on repository ZupIT / charlescd."}`
`code: "GIT_ERROR_BRANCH_NOT_FOUND"`
`message: "Branch main not found on ZupIT / charlescd repository.`

**To Reproduce**
1. On the hypothesis board, select more than one card to generate a release;
2. Name the release and click "generate release";
3. See error

**Expected behavior**
When selecting more than one card for the release generation, as long as they do not conflict with each other and are within acceptable standards (conflicts resolved), the generation of the release with more than one card (branch) should be allowed

**Screenshots**
![image](https://user-images.githubusercontent.com/42280930/104048930-cf65e980-51c2-11eb-981d-93bb6877e106.png)

![image](https://user-images.githubusercontent.com/42280930/104049024-f91f1080-51c2-11eb-98a3-ffb048aa07c7.png)

**Comment by ifdouglas** [comment]
This issue is referencing the Hypothesis Board, and this Module/Page will be removed in near future release.
