### ISSUE TITLE
When logging in with a user associated with a release deployed in an old charles circle, it is not possible to login

### ISSUE THREAD

**Issue by iezadamascenozup** [ZupIT/charlescd#785]
**Describe the bug**
Accessing charles and deploying a release in an old circle, when accessing this version with a user belonging to the rule of that old circle, the authentication api fails showing a 503

**To Reproduce**
1. Access an old circle
2. Deploy a new release
3. Associate a user with that circle
4. Try logging in with the associated user
5. See error

**Expected behavior**
Regardless of whether or not it is an old cycle, the system should not present an authentication error

**Screenshots**
![image](https://user-images.githubusercontent.com/42280930/104052299-43ef5700-51c8-11eb-8ba7-cc3e8d039975.png)
![image](https://user-images.githubusercontent.com/42280930/104052823-08a15800-51c9-11eb-9d07-3a6240672084.png)

**Comment by monicaribeiro** [comment]
This issue is caused by another issue.
