### ISSUE TITLE
Fix GitHub Charles CD README logo for dark mode

### ISSUE THREAD

**Issue by ifdouglas** [ZupIT/charlescd#839]
**Describe the bug**
When use GitHub in dark mode, the logo in README is not clearly visible.

**To Reproduce**
Enter in [Charles CD GitHub repo](https://github.com/ZupIT/charlescd) with dark mode enabled.

**Expected behavior**
When use GitHub in dark mode, the logo in README needs to be clearly visible.

**Screenshots**
![logo-dark-mode](https://user-images.githubusercontent.com/69310124/106176915-a3f96d80-6176-11eb-8c32-569cd4a9aae9.PNG)

**Your Environment**
- OS: Windows 10
- Browser Name and version: Firefox 84.0.2 (64-bits)

**Comment by luanecavalcantizup** [comment]
It is in the github backlog to address this feature of theme context for images in dark and light mode https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/59
