### ISSUE TITLE
Inconsistently highlighting Circle menu item after choose an incomplete Workspace

### ISSUE THREAD

**Issue by ifdouglas** [ZupIT/charlescd#904]
**Describe the bug**
After choose an incomplete Workspace, the internal menu incorrect highlight the inactive Circle menu item.

---
**To Reproduce**
1. Login with a root/maintainer user
2. Choose an incomplete Workspace
3. See the highlighted menu go to Circle

**Expected behavior**
When choose an incomplete Workspace, the highlighted menu needs to be Settings.

**Screenshots**
<img width="443" alt="Screen Shot 2021-02-11 at 14 46 33" src="https://user-images.githubusercontent.com/69310124/107676476-f1e29b00-6c77-11eb-8c10-183497824c47.png">

**Comment by luanecavalcantizup** [comment]
@ifdouglas

**Comment by SchumaiquerZup** [comment]
problem no longer occurs in version https://github.com/ZupIT/charlescd/releases/tag/1.0.1
