### ISSUE TITLE
Deploy does not happen because of my tag name

### ISSUE THREAD

**Issue by monicaribeiro** [ZupIT/charlescd#917]
**Describe the bug**
When I type a release name like `testCircle3` the deployment fails. When I check Octopipe logs, I see the following error:
```
time="2021-02-18T19:23:34Z" level=info msg="ERROR:DO_DEPLOYMENT" error="Deployment.apps \"beagle-movies-bff-circleTest3-543933f6-f2f1-49b7-8a54-c78493d147c1\" is invalid: metadata.name: Invalid value: \"beagle-movies-bff-circleTest3-543933f6-f2f1-49b7-8a54-c78493d147c1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" function=applyV2Manifest
```

**To Reproduce**
1. Type a name for the release. 
2. Select a module. 
3. Select a component. 
4. Version name: testCircle3. 
5. Click on 'deploy' button.
4. See error on Octopipe log.

**Expected behavior**
I was expecting one of the two behaviors:
1. Receive on the UI an error message saying that my tag name does fit the Kubernetes requirements.
or
2. Have a validator on the UI saying that the image exists but can not be used because of the kubernetes requirements.

Besides that, I think that would be amazing to know the description of the requirement: `subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character `

**Comment by cpgo** [comment]
Added the `butler` label because we have to validate it on the backend too.

**Comment by SchumaiquerZup** [comment]
resolved in https://github.com/ZupIT/charlescd/pull/1246
