### ISSUE TITLE
Documentation website not openning

### ISSUE THREAD

**Issue by diogomqbm** [ZupIT/charlescd#93]
**Describe the bug**
When trying to access https://charlescd.io/ I get a blank page and multiple errors in the console.

**To Reproduce**
1. Type https://charlescd.io/ in browser URL
2. See error

**Expected behavior**
Expected to open the official documentation website.

**Screenshots**
![image](https://user-images.githubusercontent.com/18554242/83775022-d9d46980-a65c-11ea-8c6c-403795831a96.png)

![image](https://user-images.githubusercontent.com/18554242/83775073-eb1d7600-a65c-11ea-9a86-fc5c932e7064.png)

**Your Environment**
- Browser Name and version: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- OS Name and Version: macOS Catalina Version 10.15.4

**Additional context**
I asked a few friends about this and they were able to access the official docs just fine. I don't know why this is happening only with me.

**Comment by monicarib** [comment]
@diogomqbm Thank you for reporting this issue :) We are investigating it.

**Comment by williamokano** [comment]
Documentation link seems to be broken: `https://charlescd.io/Link%20documenta%C3%A7%C3%A3o`

Getting the following error:

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>137F5AAB501A8D07</RequestId>
<HostId>7pbE0QgUPmeY96+8OeXnYJY+7eQnVgTpBM/GmRMax7r//yMBoqWhX28zL0YffsLJrttQeoLgadw=</HostId>
</Error>
```

**Comment by washingtonsoares** [comment]
Hi @diogomqbm,
Is the problem still happening for you?

**Comment by diogomqbm** [comment]
@washingtonsoares no, thanks for fixing it!
