### ISSUE TITLE
Broken link in docs - section getting started

### ISSUE THREAD

**Issue by s4rd1nh4** [ZupIT/charlescd#96]
**Describe the bug**
Broken link in docs - section getting started

**To Reproduce**
1. Go to https://docs.charlescd.io/v/v0.2.1/primeiros-passos/instalando-charles
2. Click in "customizacão" ( https://docs.charlescd.io/primeiros-passos/instalando-charles#customizacao-total )
3. See error

**Expected behavior**
Show the page

**Screenshots**

**Your Environment**
- CharlesCD version used:
- Description of environment where CharlesCD is running:
- Browser Name and version (if applicable):

**Additional context**

**Comment by monicarib** [comment]
Hi, @s4rd1nh4 
Thank you for reporting this issue :) We made the changes at documentation.
