### ISSUE TITLE
Notifications keeps showing until user closes it

### ISSUE THREAD

**Issue by luanecavalcantizup** [ZupIT/charlescd#993]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but would be an improvement to the user interface.

**Describe the solution you'd like**
A notification showing a successful message, should automatically disappear after some seconds.

**Additional context**
![image](https://user-images.githubusercontent.com/74269773/111152067-12e82580-856f-11eb-83ca-916605215875.png)

**Comment by SchumaiquerZup** [comment]
Based on a usability survey we concluded that the bar should not disappear
